name: Deploy RapidWork Frontend React [Azure]

on:
  push:
    branches:
      - master

jobs:
  dockerize-and-upload:
    runs-on: ubuntu-22.04

    steps:
      - name: Copiar el repositorio
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Autenticación en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir la imagen y subirla a DockerHub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/rapid-work:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/rapid-work:latest
          file: ./dockerfile
          context: .

  azure-deploy-app-services:
    needs: dockerize-and-upload
    runs-on: ubuntu-22.04

    steps:
      - name: Autenticación en Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Deploy to Azure Web App for Container"
        uses: azure/webapps-deploy@v2
        with:
          app-name: RapidWork
          images: ${{ secrets.DOCKERHUB_USERNAME }}/rapid-work:latest
